---
- name: Setting facts for master
  ansible.builtin.set_fact:
    master_address: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"

- name: Setting facts for slave
  ansible.builtin.set_fact:
    slave_address: "{{ groups['slave'] | map('extract', hostvars, 'ansible_host') | list }}"

- name: Ensure replication user exists on master
  community.mysql.mysql_user:
    name: "{{ mysql_replication_user.name }}"
    host: "{{ item }}"
    password: "{{ mysql_replication_user.password }}"
    login_unix_socket: "{{ mysql_login_unix_socket }}"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    state: present
  loop: "{{ slave_address }}"
  no_log: true
  when:
    - mysql_replication_user.name is defined
    - inventory_hostname in groups['master']

- name: Check slave replication status
  community.mysql.mysql_replication:
    mode: getreplica
    login_unix_socket: "{{ mysql_login_unix_socket }}"
  register: slave_status
  when:
    - inventory_hostname in groups['slave']

- name: Check master replication status
  community.mysql.mysql_replication:
    mode: getprimary
    login_unix_socket: "{{ mysql_login_unix_socket }}"
  register: master_status
  when:
    - inventory_hostname in groups['master']

- name: Configure replication on the slave
  community.mysql.mysql_replication:
    mode: changeprimary
    primary_host: "{{ master_address }}"
    primary_user: "{{ mysql_replication_user.name }}"
    primary_password: "{{ mysql_replication_user.password }}"
    primary_auto_position: true
    login_unix_socket: "{{ mysql_login_unix_socket }}"
  no_log: true
  register: configure_replica
  when:
    - inventory_hostname in groups['slave']
    - mysql_replication_user.name is defined

- name: Start replication
  community.mysql.mysql_replication:
    mode: startreplica
    login_unix_socket: "{{ mysql_login_unix_socket }}"
  when:
    - inventory_hostname in groups['slave']
