---
- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 300

- name: Add Percona Repository
  ansible.builtin.apt:
    autoremove: true
    update_cache: true
    deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_lsb.codename }}_all.deb"
    state: present

- name: Check if Percona repository already configured
  ansible.builtin.command: "percona-release show"
  register: percona_release_show
  changed_when: false
  failed_when: false

- name: "Enable Percona repository"
  ansible.builtin.command: "percona-release setup ps-{{ version | replace('.', '') }}"
  changed_when: true
  when: "'ps-' ~ (version | replace('.', '')) not in percona_release_show.stdout"

- name: Install Percona Server packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ percona_packages }}"
  notify:
    - restart_percona

- name: Install PyMySQL via apt
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
