---
- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 300

- name: Add Percona Repository
  ansible.builtin.apt:
    autoremove: true
    update_cache: true
    deb: https://repo.percona.com/apt/percona-release_latest.{{ ansible_lsb.codename }}_all.deb
    state: present

- name: "Enable Percona repository"
  ansible.builtin.command: "percona-release setup ps-{{ version | replace('.', '') }}"
  changed_when: true

- name: Install Percona Server
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - '{{ percona_packages }}'
  notify:
    - reload_percona

- name: Install PyMySQL via apt
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
