---
- name: Restart percona service
  ansible.builtin.service:
    name: "{{ mysql_daemon }}"
    state: restarted
    enabled: true
  listen: restart_percona

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Reload systemd

- name: Restart mysqld_exporter
  ansible.builtin.service:
    name: mysqld_exporter
    state: restarted

